deploymentTool: getambassador.io
fullnameOverride: emissary-ingress
podAnnotations:
  consul.hashicorp.com/connect-inject: 'false'
  sidecar.istio.io/inject: 'false'
containerNameOverride: ambassador
restartPolicy: Always
terminationGracePeriodSeconds: "0"
service:
  type: LoadBalancer

  # TODO(lukeshu): It's silly that we need to set this, but the OSS
  # Helm chart breaks if you set deploymentTool="getambassador.io"
  # without setting service.selector.  We should fix that, but until
  # then, just explicitly set this to what would be (if not for
  # deploymentTool) the default value.
  selector:
    app.kubernetes.io/name: emissary-ingress
    app.kubernetes.io/instance: emissary-ingress

replicaCount: 3
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchLabels:
            service: ambassador
        topologyKey: kubernetes.io/hostname
      weight: 100

resources:
  limits:
    cpu: 1
    memory: 400Mi
  requests:
    memory: 100Mi
adminService:
  type: NodePort
